on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          go get filippo.io/mkcert
          make cert
      - name: Test
        run: go test ./...
